apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

resources:
  - apps-domain-tls.yaml
  - apps-domain-tls-cert.yaml
  - patch-default-ingress-controller.yaml